# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('subunit', models.IntegerField()),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('content', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=30)),
                ('score', models.IntegerField(null=True)),
                ('region', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tweets.Region')),
            ],
        ),
    ]
