# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0002_auto_20160220_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
