# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0002_region_pulled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='score',
            new_name='finalScore',
        ),
        migrations.AddField(
            model_name='region',
            name='tweetScore',
            field=models.IntegerField(null=True),
        ),
    ]
