# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:32
from __future__ import unicode_literals

import Tweets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0003_auto_20160220_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('subunit', models.IntegerField()),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tweet',
            name='region',
            field=models.ForeignKey(default=Tweets.models.Region, on_delete=django.db.models.deletion.CASCADE, to='Tweets.Region'),
        ),
    ]
