# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0004_auto_20160224_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tweets.Region'),
        ),
    ]
